apiVersion: v1
kind: Service
metadata:
  name: "marcinjahn-website"
  labels:
    app: "marcinjahn-website"
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: "marcinjahn-website"
